# Generated by Django 3.2 on 2022-10-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221019_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student',
        ),
    ]
